### ISSUE TITLE
linux：make check errors

### ISSUE THREAD

**Issue by AHoou** [usnistgov/SCTK#25]
@giuliopaci @jeromeajot @guyer @mdsteveb @agmorey Hi,I met a problem when I run "make check":

_**...
make[2]: Leaving directory '/workspaces/SCTK/src/rfilter1'
(cd csrfilt && make check)
make[2]: Entering directory '/workspaces/SCTK/src/csrfilt'
Testing csrfilt.sh
./RunTests.pl
make[2]: execvp: ./RunTests.pl: Permission denied
makefile:18: recipe for target 'check' failed
make[2]: *** [check] Error 127
make[2]: Leaving directory '/workspaces/SCTK/src/csrfilt'
makefile:87: recipe for target 'checkFast' failed
make[1]: *** [checkFast] Error 2
make[1]: Leaving directory '/workspaces/SCTK/src'
makefile:51: recipe for target 'check' failed
make: *** [check] Error 2**_

Do you konw how to solve this problem?
when I run “$ chmod -R 777 ./src/*” and "$ make check " I still got errors like that:

**_...
make[2]: Entering directory '/workspaces/SCTK/src/hubscr'
Testing hubscr.pl
./RunTests.pl
   Running test 'test1-sastt', operation 'test', options '-G -f rttm -F rttm -a', directory 'test1-sastt.test'
      Executing command
      Comparing output
[ERROR] Test test1-sastt has failed.  Diff output is :
Only in test1-sastt.test/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d\*_NONE_1.html
 Only in test1-sastt.base/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d__NONE_1.html

makefile:19: recipe for target 'check' failed
make[2]: *** [check] Error 1
make[2]: Leaving directory '/workspaces/SCTK/src/hubscr'
makefile:87: recipe for target 'checkFast' failed
make[1]: *** [checkFast] Error 2
make[1]: Leaving directory '/workspaces/SCTK/src'
makefile:51: recipe for target 'check' failed
make: *** [check] Error 2_**

How to solve these?

**Comment by AHoou** [comment]
Ok, fine. I fix this error by myself.

1. If you guys have met the error of "Permission denied", I  think can fix it by run "$ chmod -R 777 ./src/*" which is rude but it is effective.

2. I rename the "SCTK/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d__NONE_1.html"  
to "SCTK/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d\\*_NONE_1.html" 
by run "$ mv SCTK/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d__NONE_1.html  SCTK/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d\\*_NONE_1.html "  

(ps: before '*' ,there is a '\\',which is can't be display in the github html page)

 3. I think it is the name 'SCTK/src/hubscr/test1-sastt.test/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d\*_NONE_1.html' is different from the name 'SCTK/src/hubscr/test1-sastt.test/sastt-case1.sys.rttm.filt.alignments: ICSI_20011030-1030_d__NONE_1.html' in my system.

**Comment by mdsteveb** [comment]
Hi, just a comment: github admins receive tons of notifications so I never saw that you had tagged me in your question. I’m glad you were able to solve it yourself.

Suggestions:
1. Don’t use 777 for permissions!  Try 644 on files and 755 on directories.
2. Beware of special characters in file names. I would probably not put a colon (:) or asterix (*) in a file name unless there was no other way. Also beware question marks (?) and quotes. The only character you absolutely can’t have in a Linux file name is a slash (/) since that separates path components, but other characters tend to be interpreted by the shell when you’re working on the command line, and do weird things if you don’t quote or escape them.
